In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.datasets import load_digits 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt


In [2]:
df =load_digits()
x=df.data
y=df.target
x.shape

(1797, 64)

## Split the data into training and Dataset

In [3]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

## "GAUSSIAN KERNEL"

In [4]:
model=SVC(kernel='rbf')

In [5]:
model.fit(x_train,y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [6]:
pred=model.predict(x_test)

## CLASSIFICATION REPORT

In [7]:
print(metrics.classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      0.44      0.61        43
          1       1.00      0.73      0.84        37
          2       1.00      0.79      0.88        38
          3       1.00      0.74      0.85        46
          4       1.00      0.27      0.43        55
          5       1.00      0.02      0.03        59
          6       1.00      0.71      0.83        45
          7       1.00      0.66      0.79        41
          8       0.15      1.00      0.26        38
          9       1.00      0.25      0.40        48

avg / total       0.93      0.52      0.57       450



## CONFUSION MATRIX

In [8]:
print("Confusion Matrix",confusion_matrix(y_test, pred))

Confusion Matrix [[19  0  0  0  0  0  0  0 24  0]
 [ 0 27  0  0  0  0  0  0 10  0]
 [ 0  0 30  0  0  0  0  0  8  0]
 [ 0  0  0 34  0  0  0  0 12  0]
 [ 0  0  0  0 15  0  0  0 40  0]
 [ 0  0  0  0  0  1  0  0 58  0]
 [ 0  0  0  0  0  0 32  0 13  0]
 [ 0  0  0  0  0  0  0 27 14  0]
 [ 0  0  0  0  0  0  0  0 38  0]
 [ 0  0  0  0  0  0  0  0 36 12]]


## Accuracy

In [9]:
accuracy_score = model.score(x_test, y_test)
print("The accuracy score is : {}".format(accuracy_score)) 

The accuracy score is : 0.5222222222222223


## Score

In [10]:
model.score(x_test,y_test)

0.5222222222222223

## "POLY KERNEL"

In [11]:
model2=SVC(kernel='poly',degree=6)

In [12]:
model2.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=6, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
pred2=model2.predict(x_test)

## CLASSIFICATION REPORT

In [14]:
print(classification_report(y_test,pred2))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        43
          1       0.95      0.97      0.96        37
          2       1.00      1.00      1.00        38
          3       0.98      0.96      0.97        46
          4       1.00      1.00      1.00        55
          5       0.98      1.00      0.99        59
          6       1.00      1.00      1.00        45
          7       0.98      0.98      0.98        41
          8       0.95      0.92      0.93        38
          9       0.96      0.96      0.96        48

avg / total       0.98      0.98      0.98       450



## CONFUSION MATRIX

In [15]:
print("Confusion Matrix",confusion_matrix(y_test, pred2))

Confusion Matrix [[43  0  0  0  0  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  1  0]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  0 44  0  1  0  0  1  0]
 [ 0  0  0  0 55  0  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  0  0]
 [ 0  0  0  0  0  0 45  0  0  0]
 [ 0  0  0  0  0  0  0 40  0  1]
 [ 0  2  0  0  0  0  0  0 35  1]
 [ 0  0  0  1  0  0  0  1  0 46]]


## Accuracy

In [16]:
accuracy_score = model2.score(x_test, y_test)
print("The accuracy score is : {}".format(accuracy_score)) 

The accuracy score is : 0.98


## Score

In [17]:
model2.score(x_test,y_test)

0.98

## "LINEAR KERNEL"

In [18]:
model3=SVC(kernel='linear')

In [19]:
model3.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [20]:
pred3=model3.predict(x_test)

## CLASSIFICATION REPORT

In [21]:
print ("Classification Report", classification_report(y_test, pred3)) 

Classification Report              precision    recall  f1-score   support

          0       1.00      1.00      1.00        43
          1       0.97      1.00      0.99        37
          2       0.97      1.00      0.99        38
          3       0.98      0.93      0.96        46
          4       1.00      0.98      0.99        55
          5       0.97      1.00      0.98        59
          6       1.00      1.00      1.00        45
          7       0.98      0.98      0.98        41
          8       1.00      0.97      0.99        38
          9       0.96      0.96      0.96        48

avg / total       0.98      0.98      0.98       450



## CONFUSION MATRIX

In [22]:
print("Confusion Matrix",confusion_matrix(y_test, pred3))

Confusion Matrix [[43  0  0  0  0  0  0  0  0  0]
 [ 0 37  0  0  0  0  0  0  0  0]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  1 43  0  1  0  0  0  1]
 [ 0  1  0  0 54  0  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  0  0]
 [ 0  0  0  0  0  0 45  0  0  0]
 [ 0  0  0  0  0  0  0 40  0  1]
 [ 0  0  0  0  0  1  0  0 37  0]
 [ 0  0  0  1  0  0  0  1  0 46]]


## Accuracy

In [23]:
accuracy_score = model3.score(x_test, y_test)
print("The accuracy score is : {}".format(accuracy_score)) 

The accuracy score is : 0.9822222222222222


## Score

In [24]:
model3.score(x_test,y_test)

0.9822222222222222

## "SIGMOID KERNEL"

In [25]:
model4=SVC(kernel='sigmoid')

In [26]:
model4.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [27]:
pred4=model4.predict(x_test)

## CLASSIFICATION REPORT

In [28]:
print ("Classification Report", classification_report(y_test, pred4)) 

Classification Report              precision    recall  f1-score   support

          0       0.00      0.00      0.00        43
          1       0.08      1.00      0.15        37
          2       0.00      0.00      0.00        38
          3       0.00      0.00      0.00        46
          4       0.00      0.00      0.00        55
          5       0.00      0.00      0.00        59
          6       0.00      0.00      0.00        45
          7       0.00      0.00      0.00        41
          8       0.00      0.00      0.00        38
          9       0.00      0.00      0.00        48

avg / total       0.01      0.08      0.01       450



C:\Users\NIK\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## CONFUSION MATRIX

In [29]:
print("Confusion Matrix",confusion_matrix(y_test, pred4))

Confusion Matrix [[ 0 43  0  0  0  0  0  0  0  0]
 [ 0 37  0  0  0  0  0  0  0  0]
 [ 0 38  0  0  0  0  0  0  0  0]
 [ 0 46  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  0  0]
 [ 0 59  0  0  0  0  0  0  0  0]
 [ 0 45  0  0  0  0  0  0  0  0]
 [ 0 41  0  0  0  0  0  0  0  0]
 [ 0 38  0  0  0  0  0  0  0  0]
 [ 0 48  0  0  0  0  0  0  0  0]]


## Accuracy

In [30]:
accuracy_score = model4.score(x_test, y_test)
print("The accuracy score is : {}".format(accuracy_score)) 

The accuracy score is : 0.08222222222222222


## Score

In [31]:
model4.score(x_test,y_test)

0.08222222222222222