In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.naive_bayes import MultinomialNB


## probability of (yes/sunny)
##p of sunny 5/14
##p y of play 9/14
##p n 5/14
#p(y/sunny)= p(y)*p(sunny/y)/p(sunny)

In [2]:

p =(9/14*(3/9))/(5/14)
p

0.6

In [3]:
iris=load_iris()
x=iris.data
y =iris.target

## splitting the dataset

In [4]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

## GuassianNB

In [5]:
model=GaussianNB()

In [6]:
model.fit(X_train,y_train)

GaussianNB(priors=None)

In [7]:
pred=model.predict(X_test)

## Confusion Matrix

In [8]:
matrix=confusion_matrix(y_test,pred)
print(matrix)

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


## Classification Report

In [9]:
report1=classification_report(y_test,pred)

In [10]:
print(report1)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       1.00      1.00      1.00        11
          2       1.00      1.00      1.00        12

avg / total       1.00      1.00      1.00        38



## MultinomialNB

In [11]:
model=MultinomialNB()

In [12]:
model.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [13]:
pred=model.predict(X_test)

## Confusion Matrix

In [14]:
matrix=confusion_matrix(y_test,pred)
print(matrix)

[[15  0  0]
 [ 0 11  0]
 [ 0  1 11]]


## Classification Report

In [15]:
report1=classification_report(y_test,pred)
print(report1)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       0.92      1.00      0.96        11
          2       1.00      0.92      0.96        12

avg / total       0.98      0.97      0.97        38

