# SPAM Classifier
Dataset-https://drive.google.com/file/d/18TGGVR4TqYLY2_sI4sRWMz4ncOidr0Ju/view?usp=sharing/

In [1]:
import pandas as pd

## Reading table 

In [2]:
df=pd.read_csv("C:/Users/NIK/Desktop/ML_learning/project/spam.csv",encoding="latin1")
df

class                                                SMS
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
6      ham  Even my brother is not like to speak with me. ...
7      ham  As per your request 'Melle Melle (Oru Minnamin...
8     spam  WINNER!! As a valued network customer you have...
9     spam  Had your mobile 11 months or more? U R entitle...
10     ham  I'm gonna be home soon and i don't want to tal...
11    spam  SIX chances to win CASH! From 100 to 20,000 po...
12    spam  URGENT! You have won a 1 week FREE membership ...
13     ham  I've been searching for the right words to tha...
14     ham                I HAVE A DATE ON SUNDAY WITH WILL!!
15    spam  XXXMobileMovieClub: To use your credit, click ...
16     ham                         Oh k...i'm watching here:)
17     ham  Eh u remember how 2 spell his name... Yes i di...
18     ham  Fine if thatåÕs the way u feel. ThatåÕs the wa...
19    spam  England v Macedonia - dont miss the goals/team...
20     ham          Is that seriously how you spell his name?
21     ham  I‰Û÷m going to try for 2 months ha ha only joking
22     ham  So Ì_ pay first lar... Then when is da stock c...
23     ham  Aft i finish my lunch then i go str down lor. ...
24     ham  Ffffffffff. Alright no way I can meet up with ...
25     ham  Just forced myself to eat a slice. I'm really ...
26     ham                     Lol your always so convincing.
27     ham  Did you catch the bus ? Are you frying an egg ...
28     ham  I'm back &amp; we're packing the car now, I'll...
29     ham  Ahhh. Work. I vaguely remember that! What does...
...    ...                                                ...
5542   ham           Armand says get your ass over to epsilon
5543   ham             U still havent got urself a jacket ah?
5544   ham  I'm taking derek &amp; taylor to walmart, if I...
5545   ham      Hi its in durban are you still on this number
5546   ham         Ic. There are a lotta childporn cars then.
5547  spam  Had your contract mobile 11 Mnths? Latest Moto...
5548   ham                 No, I was trying it all weekend ;V
5549   ham  You know, wot people wear. T shirts, jumpers, ...
5550   ham        Cool, what time you think you can get here?
5551   ham  Wen did you get so spiritual and deep. That's ...
5552   ham  Have a safe trip to Nigeria. Wish you happines...
5553   ham                        Hahaha..use your brain dear
5554   ham  Well keep in mind I've only got enough gas for...
5555   ham  Yeh. Indians was nice. Tho it did kane me off ...
5556   ham  Yes i have. So that's why u texted. Pshew...mi...
5557   ham  No. I meant the calculation is the same. That ...
5558   ham                             Sorry, I'll call later
5559   ham  if you aren't here in the next  &lt;#&gt;  hou...
5560   ham                  Anything lor. Juz both of us lor.
5561   ham  Get me out of this dump heap. My mom decided t...
5562   ham  Ok lor... Sony ericsson salesman... I ask shuh...
5563   ham                                Ard 6 like dat lor.
5564   ham  Why don't you wait 'til at least wednesday to ...
5565   ham                                       Huh y lei...
5566  spam  REMINDER FROM O2: To get 2.50 pounds free call...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

## Dividing SMS and class

In [3]:
X=pd.DataFrame(df['SMS'])
X

SMS
0     Go until jurong point, crazy.. Available only ...
1                         Ok lar... Joking wif u oni...
2     Free entry in 2 a wkly comp to win FA Cup fina...
3     U dun say so early hor... U c already then say...
4     Nah I don't think he goes to usf, he lives aro...
5     FreeMsg Hey there darling it's been 3 week's n...
6     Even my brother is not like to speak with me. ...
7     As per your request 'Melle Melle (Oru Minnamin...
8     WINNER!! As a valued network customer you have...
9     Had your mobile 11 months or more? U R entitle...
10    I'm gonna be home soon and i don't want to tal...
11    SIX chances to win CASH! From 100 to 20,000 po...
12    URGENT! You have won a 1 week FREE membership ...
13    I've been searching for the right words to tha...
14                  I HAVE A DATE ON SUNDAY WITH WILL!!
15    XXXMobileMovieClub: To use your credit, click ...
16                           Oh k...i'm watching here:)
17    Eh u remember how 2 spell his name... Yes i di...
18    Fine if thatåÕs the way u feel. ThatåÕs the wa...
19    England v Macedonia - dont miss the goals/team...
20            Is that seriously how you spell his name?
21    I‰Û÷m going to try for 2 months ha ha only joking
22    So Ì_ pay first lar... Then when is da stock c...
23    Aft i finish my lunch then i go str down lor. ...
24    Ffffffffff. Alright no way I can meet up with ...
25    Just forced myself to eat a slice. I'm really ...
26                       Lol your always so convincing.
27    Did you catch the bus ? Are you frying an egg ...
28    I'm back &amp; we're packing the car now, I'll...
29    Ahhh. Work. I vaguely remember that! What does...
...                                                 ...
5542           Armand says get your ass over to epsilon
5543             U still havent got urself a jacket ah?
5544  I'm taking derek &amp; taylor to walmart, if I...
5545      Hi its in durban are you still on this number
5546         Ic. There are a lotta childporn cars then.
5547  Had your contract mobile 11 Mnths? Latest Moto...
5548                 No, I was trying it all weekend ;V
5549  You know, wot people wear. T shirts, jumpers, ...
5550        Cool, what time you think you can get here?
5551  Wen did you get so spiritual and deep. That's ...
5552  Have a safe trip to Nigeria. Wish you happines...
5553                        Hahaha..use your brain dear
5554  Well keep in mind I've only got enough gas for...
5555  Yeh. Indians was nice. Tho it did kane me off ...
5556  Yes i have. So that's why u texted. Pshew...mi...
5557  No. I meant the calculation is the same. That ...
5558                             Sorry, I'll call later
5559  if you aren't here in the next  &lt;#&gt;  hou...
5560                  Anything lor. Juz both of us lor.
5561  Get me out of this dump heap. My mom decided t...
5562  Ok lor... Sony ericsson salesman... I ask shuh...
5563                                Ard 6 like dat lor.
5564  Why don't you wait 'til at least wednesday to ...
5565                                       Huh y lei...
5566  REMINDER FROM O2: To get 2.50 pounds free call...
5567  This is the 2nd time we have tried 2 contact u...
5568              Will Ì_ b going to esplanade fr home?
5569  Pity, * was in mood for that. So...any other s...
5570  The guy did some bitching but I acted like i'd...
5571                         Rofl. Its true to its name

[5572 rows x 1 columns]

In [4]:
Y=pd.DataFrame(df["class"])
Y

class
0      ham
1      ham
2     spam
3      ham
4      ham
5     spam
6      ham
7      ham
8     spam
9     spam
10     ham
11    spam
12    spam
13     ham
14     ham
15    spam
16     ham
17     ham
18     ham
19    spam
20     ham
21     ham
22     ham
23     ham
24     ham
25     ham
26     ham
27     ham
28     ham
29     ham
...    ...
5542   ham
5543   ham
5544   ham
5545   ham
5546   ham
5547  spam
5548   ham
5549   ham
5550   ham
5551   ham
5552   ham
5553   ham
5554   ham
5555   ham
5556   ham
5557   ham
5558   ham
5559   ham
5560   ham
5561   ham
5562   ham
5563   ham
5564   ham
5565   ham
5566  spam
5567  spam
5568   ham
5569   ham
5570   ham
5571   ham

[5572 rows x 1 columns]

### FEATURE EXTRACTION USING TF-IDF

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
textfeatures=df["SMS"].copy()
vectorize = TfidfVectorizer()

In [7]:
features=vectorize.fit_transform(textfeatures)

In [8]:
type(features)

scipy.sparse.csr.csr_matrix

### STRATIFIED SPLIT FUNCTION
For Splitting dataset for equal distribution

In [9]:
from sklearn.model_selection import StratifiedShuffleSplit

In [10]:
s=StratifiedShuffleSplit(n_splits=3, test_size=0.5, random_state=11)
Y=Y.values.reshape(5572)

In [11]:
s.get_n_splits(X,Y)

3

In [12]:
for train_index, test_index in s.split(features, Y):
  print ("TRAIN:", train_index, "TEST:", test_index)
X_train, X_test = features[train_index], features[test_index]  
Y_train, Y_test = Y[train_index], Y[test_index]

TRAIN: [4056 3513 1573 ... 3180  742 3477] TEST: [4993 5537 1775 ...  967 2798 4698]
TRAIN: [1121 3165 1720 ... 3488 5227  659] TEST: [2212 1188 5171 ... 2379 1218  284]
TRAIN: [3896 3618 4933 ... 1550 3182 4640] TEST: [5436 4461 1216 ... 1902  264 4158]


# Use different standard classifiers for classification of the texts.

## KNeighbour Classifier

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
model=KNeighborsClassifier()

In [15]:
model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

### Fit the data

In [16]:
model.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

### Predict

In [17]:
KNN_pred = model.predict(X_test)

In [18]:
from sklearn  import model_selection

In [19]:
result = pd.DataFrame({"Predicted":KNN_pred ,"Actual":Y_test})
result
KFold=model_selection.KFold(n_splits=10,random_state=7)
KFold

KFold(n_splits=10, random_state=7, shuffle=False)

### Accuracy

In [20]:
from sklearn.metrics import accuracy_score
KNN_acc=accuracy_score(Y_test,KNN_pred)
KNN_acc

0.9615936826992103

#### Confusion matrix

In [21]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,KNN_pred)
print(matrix)


[[2408    4]
 [ 103  271]]


### F1 score

In [22]:
import numpy as np
from sklearn import metrics


In [23]:
KNN_f1 = metrics.f1_score(Y_test, KNN_pred, average='weighted', labels=np.unique(KNN_pred))
KNN_f1

0.9590505568642466

#### Confusion matrix

In [24]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,KNN_pred)
print(matrix)

[[2408    4]
 [ 103  271]]


### Classification report

In [25]:
from sklearn.metrics import classification_report

In [26]:
print(classification_report(Y_test, KNN_pred))

             precision    recall  f1-score   support

        ham       0.96      1.00      0.98      2412
       spam       0.99      0.72      0.84       374

avg / total       0.96      0.96      0.96      2786



## Naive Bayes

#### Naive Bayes classifier is a straightforward and powerful algorithm for the classification task.

## Types of Naive Bayes Algorithm

### (1)Gaussain Naive Bayes

In [27]:
from sklearn.naive_bayes import GaussianNB

In [28]:
model2=GaussianNB()
model2.fit(X_train.todense(),Y_train)

GaussianNB(priors=None)

#### Predict

In [29]:
Naive_Guas_pred= model2.predict(X_test.todense())

In [30]:
result = pd.DataFrame({"Predicted":Naive_Guas_pred ,"Actual":Y_test})
result
KFold=model_selection.KFold(n_splits=10,random_state=7)

#### Accuracy

In [31]:
gauss_acc=accuracy_score(Y_test,Naive_Guas_pred)
gauss_acc

0.9030868628858578

#### F1 score

In [32]:
bern_f1 = metrics.f1_score(Y_test, Naive_Guas_pred, average='weighted', labels=np.unique(Naive_Guas_pred))
bern_f1

0.9100293780839366

#### Confusion matrix

In [33]:
matrix = confusion_matrix(Y_test,Naive_Guas_pred)
print(matrix)

[[2196  216]
 [  54  320]]


#### Classification Report

In [34]:
print(classification_report(Y_test,Naive_Guas_pred))

             precision    recall  f1-score   support

        ham       0.98      0.91      0.94      2412
       spam       0.60      0.86      0.70       374

avg / total       0.93      0.90      0.91      2786



### (2)Bernoulli Naive Bayes

In [35]:
from sklearn.naive_bayes import BernoulliNB

#### Fit the data

In [36]:
Bern = BernoulliNB().fit(X_train,Y_train)

#### Predict

In [37]:
naive_bern_pred = Bern.predict(X_test)

#### Accuracy

In [38]:
from sklearn.metrics import accuracy_score
bern_acc=accuracy_score(Y_test,naive_bern_pred)
bern_acc

0.9720028715003589

#### Confusion matrix

In [39]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,naive_bern_pred)
print(matrix)


[[2411    1]
 [  77  297]]


#### F1 score

In [40]:
bern_f1 = metrics.f1_score(Y_test, naive_bern_pred, average='weighted', labels=np.unique(naive_bern_pred))
bern_f1

0.9706368211318986

#### Classification report

In [41]:
from sklearn.metrics import classification_report 

print(classification_report(Y_test,naive_bern_pred))

             precision    recall  f1-score   support

        ham       0.97      1.00      0.98      2412
       spam       1.00      0.79      0.88       374

avg / total       0.97      0.97      0.97      2786



### (3) Multinomial Naive Bayes

In [42]:
from sklearn.naive_bayes import MultinomialNB

In [43]:
model3=MultinomialNB()

#### Fit the data

In [44]:
model3.fit(X_train,Y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

#### Predict

In [45]:
naive_multi_pred=model3.predict(X_test)

#### Accuracy

In [46]:
multi_acc=accuracy_score(Y_test,naive_multi_pred)
multi_acc

0.9361091170136396

#### Confusion matrix

In [47]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,naive_multi_pred)
print(matrix)


[[2412    0]
 [ 178  196]]


#### F1 score

In [48]:
bern_f1 = metrics.f1_score(Y_test, naive_multi_pred, average='weighted', labels=np.unique(naive_multi_pred))
bern_f1

0.9272699751222546

#### Classification report

In [49]:
from sklearn.metrics import classification_report 

print(classification_report(Y_test,naive_multi_pred))

             precision    recall  f1-score   support

        ham       0.93      1.00      0.96      2412
       spam       1.00      0.52      0.69       374

avg / total       0.94      0.94      0.93      2786



## Decision Tree Classifier

In [50]:
from sklearn.tree import DecisionTreeClassifier

#### Fit the data

In [51]:
model4=DecisionTreeClassifier()
model4.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

#### Predict

In [52]:
Decision_pred= model.predict(X_test)

#### Accuracy

In [53]:
dis_acc=accuracy_score(Y_test,Decision_pred)
dis_acc

0.9615936826992103

#### Confusion matrix

In [54]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test,Decision_pred)
print(matrix)


[[2408    4]
 [ 103  271]]


#### F1 score

In [55]:
Multi_f1 = metrics.f1_score(Y_test, Decision_pred, average='weighted', labels=np.unique(Decision_pred))
Multi_f1

0.9590505568642466

#### Classification report

In [56]:
from sklearn.metrics import classification_report 

print(classification_report(Y_test,Decision_pred))

             precision    recall  f1-score   support

        ham       0.96      1.00      0.98      2412
       spam       0.99      0.72      0.84       374

avg / total       0.96      0.96      0.96      2786



### SVM

## Support vector machine

In [57]:
from sklearn.svm import SVC


### (1)Linear SVC


In [58]:
lsvc =SVC(kernel = "linear",degree=8)


##### Fit the data


In [59]:
lsvc.fit(X_train,Y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

#### Predict


In [60]:
lsvc_pred = lsvc.predict(X_test)

#### Accuracy

In [61]:
lsvc_acc = accuracy_score(Y_test,lsvc_pred)
lsvc_acc

0.9781048097631012

#### Confusion matrix

In [62]:
matrix = confusion_matrix(Y_test,lsvc_pred)
print(matrix)

[[2407    5]
 [  56  318]]


#### F1 score

In [63]:
lsvc_f1 = metrics.f1_score(Y_test, lsvc_pred, average='weighted', labels=np.unique(lsvc_pred))
lsvc_f1

0.977418294905242

#### Classification report

In [64]:
from sklearn.metrics import classification_report 

print(classification_report(Y_test,lsvc_pred))

             precision    recall  f1-score   support

        ham       0.98      1.00      0.99      2412
       spam       0.98      0.85      0.91       374

avg / total       0.98      0.98      0.98      2786



### (2)Poly SVC


In [65]:
psvc =SVC(kernel = "poly",degree= 8)

##### Fit the data


In [66]:
psvc.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

#### Predict


In [67]:
psvc_pred = psvc.predict(X_test)


#### Accuracy


In [68]:
psvc_acc = metrics.accuracy_score(Y_test,psvc_pred)
psvc_acc


0.8657573582196698

#### Confusion matrix


In [69]:
matrix = confusion_matrix(Y_test,psvc_pred)
print(matrix)

[[2412    0]
 [ 374    0]]


#### F1 score

In [70]:
psvc_f1 = metrics.f1_score(Y_test, psvc_pred, average='weighted', labels=np.unique(psvc_pred))
psvc_f1

0.9280492497114275

#### Classification report

In [71]:
print(classification_report(Y_test,psvc_pred))

             precision    recall  f1-score   support

        ham       0.87      1.00      0.93      2412
       spam       0.00      0.00      0.00       374

avg / total       0.75      0.87      0.80      2786



C:\Users\NIK\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### (3)Gaussian SVC

In [72]:
gsvc = SVC(kernel = 'rbf')

##### Fit the data

In [73]:
gsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

#### Predict

In [74]:
gsvc_pred = gsvc.predict(X_test)

#### Accuracy

In [75]:
gsvc_acc = metrics.accuracy_score(gsvc_pred, Y_test)
gsvc_acc

0.8657573582196698

#### Confusion matrix


In [76]:
gsvc_mat = confusion_matrix(Y_test, gsvc_pred)
gsvc_mat

array([[2412,    0],
       [ 374,    0]], dtype=int64)

#### F1 score


In [77]:
gsvc_f1 =  metrics.f1_score(Y_test, gsvc_pred, average='weighted', labels=np.unique(gsvc_pred))
gsvc_f1

0.9280492497114275

#### Classification report


In [78]:
print(classification_report(Y_test, gsvc_pred))

             precision    recall  f1-score   support

        ham       0.87      1.00      0.93      2412
       spam       0.00      0.00      0.00       374

avg / total       0.75      0.87      0.80      2786



C:\Users\NIK\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Comparing the accuracy of the classifiers using different standard classification metrics.


In [79]:
Algo_name = ["KNN","Gaussain Naive Bayes","Bernoulli Naive Bayes","Multinolmial Naive Bayes","Decision Tree Classifier",
             "Linear SVC","Poly SVC","Gaussian SVC"]
accuracy = [KNN_acc,gauss_acc,bern_acc,multi_acc,dis_acc,lsvc_acc,psvc_acc,gsvc_acc]

In [80]:
res2 = pd.DataFrame({"Algorithms":Algo_name, "Accuracy":accuracy}, index = [1,2,3,4,5,6,7,8])
res2

Algorithms  Accuracy
1                       KNN  0.961594
2      Gaussain Naive Bayes  0.903087
3     Bernoulli Naive Bayes  0.972003
4  Multinolmial Naive Bayes  0.936109
5  Decision Tree Classifier  0.961594
6                Linear SVC  0.978105
7                  Poly SVC  0.865757
8              Gaussian SVC  0.865757